// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Возвращает access token в body и refresh token в cookie\nДля доступа к api нужен access token\nВремя жизни access token - 15 минут\nВремя жизни refresh token - 30 дней\nДля обновления access token необходимо делать запрос POST /refresh с refresh token в куках",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Аутентификация"
                ],
                "summary": "Логин пользователя",
                "parameters": [
                    {
                        "description": "userData",
                        "name": "userObject",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_XTrau_auth-service_internal_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthHandlers"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Удаляет refresh token из cookie",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Аутентификация"
                ],
                "summary": "Разлогинить пользователя",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Возвращает новый access и refresh токены\nТребуется refresh токен в куках",
                "tags": [
                    "Аутентификация"
                ],
                "summary": "Обновить токены",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Регистрирует пользователя в системе\nлогиниться в системе нужно отдельно от регистрации",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Аутентификация"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "userData",
                        "name": "userObject",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_XTrau_auth-service_internal_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/auth/user": {
            "get": {
                "description": "Возвращает данные пользователя по access_token",
                "tags": [
                    "Аутентификация"
                ],
                "summary": "Получить пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Example: Bearer ",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_XTrau_auth-service_internal_dto.UserDataResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized user",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_XTrau_auth-service_internal_dto.LoginRequest": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "github_com_XTrau_auth-service_internal_dto.RegisterRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "github_com_XTrau_auth-service_internal_dto.UserDataResponse": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.AuthHandlers": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
